services:
  - type: worker
    name: telegram-bot-recordatorios
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHECK_INTERVAL_SECONDS
        value: 60
      - key: PHOTOS_REQUIRED
        value: 2